<?php
/**
 * @copyright 2019-2020 Dicr http://dicr.org
 * @author Igor A Tarasov <develop@dicr.org>
 * @license proprietary
 * @version 09.07.20 14:24:57
 */

declare(strict_types = 1);

namespace dicr\site;

use dicr\cache\CacheBehavior;
use yii\base\InvalidConfigException;
use function call_user_func;

/**
 * Базовая модель.
 *
 * @method void invalidateModelCache() очищает элементы кэша с зависимостью от класса данной модели
 *
 * @method void upsert($runValidation = true, $attributes = null) сохраняет методом upsert (без получения autogenerated
 *     ключей !!!)
 */
abstract class ActiveRecord extends \yii\db\ActiveRecord
{
    /**
     * {@inheritDoc}
     * @see \yii\base\Component::behaviors()
     */
    public function behaviors()
    {
        return array_merge(parent::behaviors(), [
            'cache' => [
                'class' => CacheBehavior::class,
            ],

            'upsert' => [
                'class' => UpsertBehavior::class
            ]
        ]);
    }

    /**
     * {@inheritDoc}
     * @see \yii\db\ActiveRecord::updateAll($attributes, $condition, $params)
     */
    public static function updateAll($attributes, $condition = '', $params = [])
    {
        parent::updateAll($attributes, $condition, $params);
        static::invalidateClassCache();
    }

    /**
     * {@inheritdoc}
     * @see \yii\db\ActiveRecord::updateAllCounters($counters, $condition, $params)
     */
    public static function updateAllCounters($counters, $condition = '', $params = [])
    {
        parent::updateAllCounters($counters, $condition, $params);
        static::invalidateClassCache();
    }

    /**
     * {@inheritdoc}
     * @see \yii\db\ActiveRecord::deleteAll($condition, $params)
     */
    public static function deleteAll($condition = null, $params = [])
    {
        parent::deleteAll($condition, $params);
        static::invalidateClassCache();
    }

    /**
     * Статический метод для очистки кэша.
     *
     * Использует invalidateModelCache
     */
    public static function invalidateClassCache()
    {
        $class = static::class;
        $instance = call_user_func([$class, 'instance']);
        $instance->invalidateModelCache();
    }

    /**
     * Создает и загружает массив моделей из табулярных данных.
     *
     * Чтобы каждый раз при сохранении не удалять/пересоздавать все табулярные модели заново,
     * можно использовать уже существующие в базе, для обновления при помощи save().
     *
     * В $current передается массив существующих в базе моделей для загрузки. Этот массив должен быть индексирован по
     * такому же ключу как и данные формы.
     *
     * В $data[$formName] передается массив данных отправленных моделей, индексированный по ключу-идентификатору
     * модели. Если модель с таким ключом отсутствует в массиве существующих ($models), то создается новая.
     *
     * Если $current не задан, то все модели будут созданы из данных.
     *
     * Модели из $current, ключ которых отсутствует в данных формы не возвращаются.
     *
     * @param array $currentModels
     * @param array $data табулярные данные, например из $_POST
     * @param string $formName
     * @return static[]
     * @throws InvalidConfigException
     */
    public static function loadAll(array $currentModels, array $data, string $formName = null)
    {
        if (empty($currentModels)) {
            $currentModels = [];
        }

        if (! isset($formName)) {
            $formName = static::instance()->formName();
        }

        // корректируем данные под форму
        if ($formName !== '') {
            $data = $data[$formName] ?? [];
        }

        $models = [];
        foreach ($data as $key => $modelData) {
            $model = $currentModels[$key] ?? new static();
            $model->load($modelData, '');
            $models[$key] = $model;
        }

        return $models;
    }
}
